import os
import re
from dotenv import load_dotenv
from faker import Faker
from playwright.sync_api import Playwright, expect

load_dotenv()
BASE_URL = os.getenv("BASE_URL")
fake = Faker()

def set_date(page, input_locator, date_str: str, year: int, day: int):
    input_locator.click()
    success = False
    hdr = page.locator(".mdt-date-picker .datepicker-header, .datepicker-header, .icon .fas, i.fas").first
    for _ in range(3):
        try:
            hdr.click()
            y = page.get_by_text(str(year))
            y.wait_for(state="visible", timeout=700)
            y.click()
            page.get_by_role("cell", name=str(day), exact=True).click()
            success = True
            break
        except:
            continue
    if not success:
        input_locator.fill(date_str)
        page.locator("body").click()

def run(playwright: Playwright) -> None:
    email1 = fake.email()
    email2 = fake.email()

    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto(BASE_URL)
    page.get_by_role("row", name="01.01.01 Kanzlei A CHF 2'900").locator("span").nth(1).click()
    with page.expect_popup() as page1_info:
        page.get_by_text("Apply").click()
    page1 = page1_info.value
    page1.get_by_text("Start").click()
    page1.locator("#parking-false").click()
    page1.locator("#car_sharing-false").click()
    page1.locator("#motorbikes-false").click()
    page1.locator("#bicycles-false").click()
    page1.locator("#wants_stockroom-false").click()
    page1.locator("#wants_workshop-false").click()
    page1.locator("#wants_coworking-false").click()
    page1.locator("#obstacle_free-false").click()
    page1.locator("#wants_homeoffice-false").click()
    page1.locator("#wants_addroom-false").click()
    page1.get_by_text("Save and next").click()
    page1.locator("#field-household_type").click()
    page1.get_by_text("couple household with child").click()
    page1.locator("#pets-false").click()
    page1.locator("#music_instruments-false").click()
    page1.locator("#smoking-false").click()
    page1.locator("#field-relocation_reason").click()
    page1.get_by_text("Change of life situation").click()
    page1.get_by_role("listitem", name="Security deposit").click()
    page1.locator("#field-source").click()
    page1.get_by_text("Real estate platform (Newhome").click()
    page1.get_by_text("Save and next").click()
    page1.get_by_text("Add adult").click()
    page1.locator("#field-title").click()
    page1.get_by_text("Mr.").click()
    page1.locator("#field-firstname").click()
    page1.locator("#field-firstname").fill("Ante")
    page1.locator("#field-name").click()
    page1.locator("#field-name").fill("Antich")
    set_date(page1, page1.locator("#field-date_of_birth"), "01.01.2000", 2000, 1)
    page1.locator("#field-civil_status").click()
    page1.get_by_text("married").click()
    page1.locator("#field-nation").click()
    page1.get_by_text("Bosnia and Herzegovina", exact=True).click()
    page1.locator("#field-permit").click()
    page1.get_by_text("(B) Residence permit").click()
    page1.locator("#field-tenant_type").click()
    page1.get_by_text("Spouse, registered partnership").click()
    page1.locator("#field-phone").click()
    page1.locator("#field-phone").fill("333333333")
    page1.locator("#field-email").click()
    page1.locator("#field-email").fill(email1)
    page1.locator("#confirm-field-email").click()
    page1.locator("#confirm-field-email").fill(email1)
    page1.locator("#field-street_nr").click()
    page1.locator("#field-street_nr").fill("12")
    page1.locator("#field-postcode").click()
    page1.locator("#field-postcode").fill("21")
    page1.locator("#field-city").click()
    page1.locator("#field-city").fill("City")
    page1.locator("#field-country").click()
    page1.get_by_text("Switzerland", exact=True).click()
    page1.locator("#field-country").click()
    page1.get_by_text("Bosnia and Herzegovina", exact=True).click()
    set_date(page1, page1.locator("#field-living_since"), "01.01.2018", 2018, 1)
    page1.locator("#legal_residence-false").click()
    page1.locator("#legal_residence-false").click()
    page1.locator("#field-employment_quota").click()
    page1.get_by_text("Full-time (90-100%)").click()
    set_date(page1, page1.locator("#field-company_since"), "01.01.2020", 2020, 1)
    page1.get_by_role("listitem", name="Not terminated").click()
    page1.locator("#field-company_street_nr").click()
    page1.locator("#field-company_street_nr").fill("98")
    page1.locator("#field-company_postcode").click()
    page1.locator("#field-company_postcode").fill("89")
    page1.locator("#field-company_city").click()
    page1.locator("#field-company_city").fill("Lab")
    page1.locator("#field-company_contact").click()
    page1.locator("#field-company_contact").fill("Ivo")
    page1.locator("#field-company_contact_phone").click()
    page1.locator("#field-company_contact_phone").fill("555555555")
    page1.locator("#field-company_contact_email").click()
    page1.locator("#field-company_contact_email").fill("ivo@ivic.com")
    page1.get_by_role("listitem", name="CreditTrust certificate").click()
    page1.locator("#field-passport_doc").get_by_role("textbox").click()
    page1.get_by_role("checkbox", name="I hereby confirm that").check()
    page1.get_by_text("Save", exact=True).click()
    page1.locator("#create-new-adult i").click()
    page1.locator("#field-title").click()
    page1.get_by_text("Ms.").click()
    page1.locator("#field-firstname").click()
    page1.locator("#field-firstname").fill("Antea")
    page1.locator("#field-name").click()
    page1.locator("#field-name").fill("Antich")
    set_date(page1, page1.locator("#field-date_of_birth"), "02.01.2000", 2000, 2)
    page1.locator("#field-civil_status").click()
    page1.get_by_text("married").click()
    page1.locator("#field-nation").click()
    page1.get_by_text("Bosnia and Herzegovina", exact=True).click()
    page1.locator("#field-permit").click()
    page1.get_by_text("(B) Residence permit").click()
    page1.locator("#field-tenant_type").click()
    page1.get_by_text("Spouse, registered partnership").click()
    page1.locator("#field-phone").click()
    page1.locator("#field-phone").fill("333333333")
    page1.locator("#field-office_phone").click()
    page1.locator("#field-office_phone").fill("")
    page1.locator("#field-email").click()
    page1.locator("#field-email").fill(email2)
    page1.locator("#confirm-field-email").click()
    page1.locator("#confirm-field-email").fill(email2)
    page1.locator("#field-street_nr").click()
    page1.locator("#field-street_nr").fill("567")
    page1.locator("#field-postcode").click()
    page1.locator("#field-postcode").fill("765")
    page1.locator("#field-city").click()
    page1.locator("#field-city").fill("Mostar")
    page1.locator("#field-country").click()
    page1.get_by_text("Bosnia and Herzegovina", exact=True).click()
    set_date(page1, page1.locator("#field-living_since"), "03.01.2019", 2019, 3)
    page1.locator("#field-employment_quota").click()
    page1.get_by_text("Full-time (90-100%)").click()
    set_date(page1, page1.locator("#field-company_since"), "06.01.2018", 2018, 6)
    page1.get_by_role("listitem", name="Not terminated").click()
    page1.locator("#field-company_street_nr").click()
    page1.locator("#field-company_street_nr").fill("434")
    page1.locator("#field-company_postcode").click()
    page1.locator("#field-company_postcode").fill("343")
    page1.locator("#field-company_city").click()
    page1.locator("#field-company_city").fill("Lab")
    page1.locator("#field-company_contact").click()
    page1.locator("#field-company_contact").fill("Mile Milich")
    page1.locator("#field-company_contact_phone").click()
    page1.locator("#field-company_contact_phone").fill("414114414")
    page1.locator("#field-company_contact_email").click()
    page1.locator("#field-company_contact_email").fill("asoldo31@gmail.com")
    page1.get_by_role("listitem", name="CreditTrust certificate").click()
    page1.get_by_role("checkbox", name="I hereby confirm that").check()
    page1.get_by_text("Save", exact=True).click()
    page1.get_by_text("Add child").click()
    page1.locator("#field-firstname").click()
    page1.locator("#field-firstname").fill("Pero")
    page1.locator("#field-name").click()
    page1.locator("#field-name").fill("Antich")
    dob = page1.locator('input[placeholder="DD.MM.YYYY"]').last
    dob.click()
    dob.fill("01.01.2021")
    page1.keyboard.press("Tab")
    page1.wait_for_timeout(150)
    page1.locator("#field-nation").click()
    page1.get_by_text("Bosnia and Herzegovina", exact=True).click()
    page1.locator("#field-days_present").fill("7")
    page1.get_by_text("Save", exact=True).click()
    page1.wait_for_load_state("networkidle")
    page1.get_by_text("Save and next").click()
    page1.get_by_role("checkbox", name="Should the prospective tenant").check()
    page1.locator("div:nth-child(3) > .boolean-field > div > .mdt-checkbox > .state").click()
    page1.get_by_role("checkbox", name="I have read the privacy").check()
    page1.get_by_text("Submit").click()
    page1.close()
    page.close()
    context.close()
    browser.close()

def test_melon_taskv1(playwright: Playwright):
    run(playwright)
