import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://mostar.api.demo.ch.melon.market/")
    page.get_by_role("row", name="01.01.01 Kanzlei A CHF 2'900").locator("span").nth(1).click()
    with page.expect_popup() as page1_info:
        page.get_by_text("Apply").click()
    page1 = page1_info.value
    page1.get_by_text("Start").click()
    page1.locator("#parking-true").click()
    page1.locator("#field-parking_regular").click()
    page1.locator("#field-parking_regular").fill("2")
    page1.locator("#field-parking_small").click()
    page1.locator("#field-parking_small").fill("1")
    page1.locator("#field-parking_large").click()
    page1.locator("#field-parking_large").fill("1")
    page1.locator("#field-parking_electric").click()
    page1.locator("#field-parking_electric").fill("2")
    page1.locator("#field-parking_electric_small").click()
    page1.locator("#field-parking_electric_small").fill("1")
    page1.locator("#field-parking_outdoor").click()
    page1.locator("#field-parking_outdoor").fill("0")
    page1.locator("#field-parking_special").click()
    page1.locator("#field-parking_special").fill("0")
    page1.get_by_role("textbox", name="Please specify").click()
    page1.get_by_role("textbox", name="Please specify").fill("0")
    page1.locator("#field-parking_special").click()
    page1.get_by_role("textbox", name="Please specify").click()
    page1.get_by_role("textbox", name="Please specify").fill("")
    page1.get_by_role("textbox", name="Please specify").click()
    page1.locator("input[type=\"file\"]").click()
    page1.locator("#car_sharing-false").click()
    page1.locator("#motorbikes-false").click()
    page1.locator("#bicycles-false").click()
    page1.locator("#wants_addroom-false").click()
    page1.locator("#wants_stockroom-false").click()
    page1.locator("#wants_workshop-false").click()
    page1.locator("#wants_coworking-false").click()
    page1.locator("#wants_homeoffice-false").click()
    page1.locator("#obstacle_free-false").click()
    page1.locator("#obstacle_free-true").click()
    page1.locator("#obstacle_free-false").click()
    page1.get_by_text("Save and next").click()
    page1.locator("#field-household_type").click()
    page1.get_by_text("couple household with child").click()
    page1.locator("#pets-false").click()
    page1.locator("#music_instruments-true").click()
    page1.locator("#field-music_instruments_type").click()
    page1.locator("#field-music_instruments_type").fill("Piano")
    page1.locator("#smoking-false").click()
    page1.locator("#field-relocation_reason").click()
    page1.get_by_text("Change of life situation").click()
    page1.locator("#field-moving_date").click()
    page1.get_by_role("listitem", name="Security deposit").click()
    page1.locator("#income_rent_ratio-true").click()
    page1.locator("#field-moving_date").click()
    page1.locator("#field-iban").click()
    page1.locator("#field-motivation").click()
    page1.locator("#field-source").click()
    page1.get_by_text("Instagram").click()
    page1.get_by_text("Save and next").click()
    page1.get_by_text("Add adult").click()
    page1.locator("#field-title").click()
    page1.get_by_text("Mr.").click()
    page1.locator("#field-firstname").click()
    page1.locator("#field-firstname").fill("Andrija")
    page1.locator("#field-name").click()
    page1.locator("#field-name").fill("Soldo")
    page1.locator("#field-date_of_birth").click()
    page1.locator("#toggle-q8d61jpx > .fas").click()
    page1.get_by_text("2000").click()
    page1.get_by_role("textbox", name="Search...").first.click()
    page1.get_by_text("December").click()
    page1.get_by_role("cell", name="15").click()
    page1.locator("#field-place_of_birth").click()
    page1.locator("#field-place_of_birth").click()
    page1.locator("#field-place_of_birth").fill("Mostar")
    page1.locator("#field-civil_status").click()
    page1.get_by_text("married").click()
    page1.locator("#field-nation").click()
    page1.locator("#field-nation").fill("croa")
    page1.get_by_text("Croatia", exact=True).click()
    page1.locator("#field-permit").click()
    page1.get_by_text("(C) Long-term resident").click()
    page1.locator("#field-living_in_country_since").click()
    page1.locator(".icon > .fas").first.click()
    page1.locator("#toggle-jqbw52f4").get_by_role("textbox", name="Search...").click()
    page1.get_by_text("2001").click()
    page1.get_by_role("cell", name="1", exact=True).click()
    page1.locator("#field-tenant_type").click()
    page1.get_by_text("Spouse, registered partnership").click()
    page1.locator("#field-phone").click()
    page1.locator("#field-phone").fill("333333333")
    page1.locator("#field-office_phone").click()
    page1.locator("#field-office_phone").fill("333333333")
    page1.locator("#field-email").click()
    page1.locator("#field-email").fill("andrija@maildrop.cc")
    page1.locator("#confirm-field-email").click()
    page1.locator("#confirm-field-email").fill("andrija@maildrop.cc")
    page1.locator("#toggle-field-current_housing_situation div").first.click()
    page1.get_by_text("Own home").click()
    page1.locator("#field-street_nr").click()
    page1.locator("#field-street_nr").fill("Ulica 1")
    page1.locator("#field-postcode").click()
    page1.locator("#field-postcode").fill("88265")
    page1.locator("#field-city").click()
    page1.locator("#field-city").fill("Bern")
    page1.locator("#field-country").click()
    page1.get_by_text("Switzerland", exact=True).click()
    page1.locator("#field-living_since").click()
    page1.locator("#toggle-54h4z20a > .fas").click()
    page1.get_by_text("2006").click()
    page1.get_by_role("cell", name="1", exact=True).click()
    page1.locator("#legal_residence-true").click()
    page1.locator("#move_three_years-false").click()
    page1.locator("#member-true").click()
    page1.locator("#member-false").click()
    page1.locator("#liability-true").click()
    page1.locator("#household_insurance-true").click()
    page1.locator("#insurance_check-true").click()
    page1.locator("#field-highest_education").click()
    page1.get_by_text("Tertiary level").click()
    page1.locator("#field-employment_quota").click()
    page1.get_by_text("Full-time (90-100%)").click()
    page1.get_by_role("listitem", name="Permanent").click()
    page1.locator("#field-company_since").click()
    page1.locator("#toggle-rdcb16wk i").click()
    page1.get_by_text("2020").click()
    page1.get_by_role("cell", name="5", exact=True).click()
    page1.get_by_role("listitem", name="Not terminated").click()
    page1.locator("#field-company_street_nr").click()
    page1.locator("#field-company_street_nr").fill("Ulica 22")
    page1.locator("#field-company_postcode").click()
    page1.locator("#field-company_postcode").fill("88265")
    page1.locator("#field-company_city").click()
    page1.locator("#field-company_city").fill("Lab")
    page1.locator("#field-company_contact").click()
    page1.locator("#field-company_contact").fill("Andrija Soldich")
    page1.locator("#field-company_contact_phone").click()
    page1.locator("#field-company_contact_phone").fill("333333333")
    page1.locator("#field-company_contact_email").click()
    page1.locator("#field-company_contact_email").fill("asoldo31@gmail.com")
    page1.locator("#field-income_range").click()
    page1.get_by_text("over CHF 200’").click()
    page1.get_by_role("listitem", name="CreditTrust certificate").click()
    page1.get_by_role("checkbox", name="I hereby confirm that").check()
    page1.get_by_text("Save", exact=True).click()
    page1.locator("#create-new-adult i").click()
    page1.locator("#field-title").click()
    page1.get_by_text("Ms.").click()
    page1.locator("#field-firstname").click()
    page1.locator("#field-firstname").fill("Andrijana")
    page1.locator("#field-name").click()
    page1.locator("#field-name").fill("Soldo")
    page1.locator("#field-date_of_birth").click()
    page1.locator("#field-date_of_birth").fill("")
    page1.locator("#field-date_of_birth").click()
    page1.locator("#toggle-8rloga4y > .fas").click()
    page1.get_by_text("September").click()
    page1.locator("#toggle-f9rf6463 i").click()
    page1.get_by_text("2001").click()
    page1.get_by_role("cell", name="1", exact=True).click()
    page1.locator("#field-civil_status").click()
    page1.get_by_text("married").click()
    page1.locator("#field-nation").click()
    page1.get_by_text("Switzerland", exact=True).click()
    page1.locator("#field-place_of_citizenship").click()
    page1.locator("#field-nation").click()
    page1.locator("#field-nation").fill("croa")
    page1.get_by_text("Croatia", exact=True).click()
    page1.locator("#field-permit").click()
    page1.get_by_text("(C) Long-term resident").click()
    page1.locator("#field-tenant_type").click()
    page1.get_by_text("Spouse, registered partnership").click()
    page1.locator("#field-phone").click()
    page1.locator("#field-phone").fill("222222222")
    page1.locator("#field-email").click()
    page1.locator("#field-email").fill("andrija@maildrop.cc")
    page1.locator("#field-email").click()
    page1.locator("#field-email").fill("andrija.soldo@fsre.sum.ba")
    page1.locator("#confirm-field-email").click()
    page1.locator("#confirm-field-email").fill("andrija.soldo@fsre.sum.ba")
    page1.locator("#field-street_nr").click()
    page1.locator("#field-street_nr").fill("11")
    page1.locator("#field-postcode").click()
    page1.locator("#field-postcode").fill("12345")
    page1.locator("#field-city").click()
    page1.locator("#field-city").fill("Basel")
    page1.locator("#field-country").click()
    page1.get_by_text("Switzerland", exact=True).click()
    page1.locator("#field-living_since").click()
    page1.locator("#toggle-yplebml5 i").click()
    page1.get_by_text("2006").click()
    page1.get_by_role("cell", name="24").click()
    page1.locator("#field-employment_quota").click()
    page1.get_by_text("Full-time (90-100%)").click()
    page1.locator("#field-company_since").click()
    page1.get_by_role("cell", name="7", exact=True).click()
    page1.get_by_role("listitem", name="Not terminated").click()
    page1.locator("#field-company_street_nr").click()
    page1.locator("#field-company_street_nr").fill("98")
    page1.locator("#field-company_postcode").click()
    page1.locator("#field-company_postcode").fill("9876")
    page1.locator("#field-company_city").click()
    page1.locator("#field-company_city").fill("Studio")
    page1.locator("#field-company_contact").click()
    page1.locator("#field-company_contact").fill("Ante Soldo")
    page1.locator("#field-company_contact_phone").click()
    page1.locator("#field-company_contact_phone").fill("555555555")
    page1.locator("#field-company_contact_email").click()
    page1.locator("#field-company_contact_email").fill("asoldo31@gmail.com")
    page1.get_by_role("listitem", name="CreditTrust certificate").click()
    page1.get_by_role("checkbox", name="I hereby confirm that").check()
    page1.get_by_text("Save", exact=True).click()
    page1.get_by_text("Add child").click()
    page1.locator("#field-firstname").click()
    page1.locator("#field-firstname").fill("Ante")
    page1.locator("#field-name").click()
    page1.locator("#field-name").fill("Soldo")
    page1.get_by_role("textbox", name="DD.MM.YYYY").click()
    page1.locator("#ykfksi78").click()
    page1.get_by_text("2023").click()
    page1.get_by_role("cell", name="3", exact=True).click()
    page1.get_by_role("textbox", name="Search...").click()
    page1.get_by_text("Switzerland").click()
    page1.locator("#increment-field-days_present").click()
    page1.locator("#increment-field-days_present").click()
    page1.locator("#increment-field-days_present").click()
    page1.locator("#increment-field-days_present i").click()
    page1.locator("#increment-field-days_present").click()
    page1.locator("#increment-field-days_present i").click()
    page1.locator("#increment-field-days_present i").click()
    page1.locator("#increment-field-days_present").click()
    page1.locator("#increment-field-days_present").click()
    page1.locator("#increment-field-days_present i").dblclick()
    page1.get_by_text("Save", exact=True).click()
    page1.get_by_text("Save and next").click()
    page1.get_by_role("checkbox", name="Should the prospective tenant").check()
    page1.get_by_role("checkbox", name="I confirm that I have").check()
    page1.get_by_role("checkbox", name="I have read the privacy").check()
    page1.get_by_text("Submit").click()
    page1.get_by_text("Thank you very much, your application has been sent. You will receive a").click()
    page1.close()
    page.close()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
