import re
from playwright.sync_api import Playwright, sync_playwright, expect


def test_run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://mostar.api.demo.ch.melon.market/")
    page.get_by_role("link", name="Phasellus").click()
    page.get_by_role("link", name="Maecenas", exact=True).click()
    page.get_by_role("link", name="Donec").click()
    page.get_by_role("link", name="Aliquam Maecenas").click()
    page.get_by_role("row", name="00.01.02 Kanzlei A CHF 1'850").locator("span").first.click()
    page.get_by_role("row", name="01.01.01 Kanzlei A CHF 2'900").locator("span").first.click()
    page.get_by_role("row", name="01.0101 Kanzlei B CHF 1'750").locator("span").first.click()
    page.locator("div:nth-child(3) > .favorite-item-header > .fa").click()
    page.locator("div:nth-child(2) > .favorite-item-header > .fa").click()
    page.locator(".favorite-item-header > .fa").click()
    page.get_by_role("row", name="03.02.02 Kanzlei B CHF 2'700").locator("i").click()
    page.get_by_role("row", name="05.0102 Kanzlei A CHF 3'300").locator("span").first.click()
    page.get_by_role("row", name="06.0523 Kanzlei A CHF 1'450").locator("span").first.click()
    page.get_by_role("row", name="06.0523 Kanzlei A CHF 1'450").locator("i").click()
    page.get_by_role("row", name="05.0102 Kanzlei A CHF 3'300").locator("i").click()
    page.get_by_role("link", name="emonitor.ch", exact=True).click()
    with page.expect_popup() as page1_info:
        page.locator(".facebook-instagram-icons > span > a").first.click()
    page1 = page1_info.value
    with page1.expect_popup() as page2_info:
        page1.get_by_role("link", name="Instagram").click()
    page2 = page2_info.value
    page2.get_by_role("link", name="qui").click()
    page2.get_by_role("row", name="06.0523 Kanzlei A CHF 1'450").locator("i").click()
    page2.evaluate("window.scrollTo(0, 0)")

    with page2.expect_popup() as page3_info:
        page2.get_by_text("Apply").click()
    page3 = page3_info.value
    page3.get_by_text("Start").click()
    page3.locator(".radio-list-item").first.click()
    page3.locator("div:nth-child(12) > .radio-field > .mdt-radio-list > .radio-list > li").first.click()
    page3.locator("div:nth-child(13) > .radio-field > .mdt-radio-list > .radio-list > li").first.click()
    page3.locator("div:nth-child(15) > .radio-field > .mdt-radio-list > .radio-list > li").first.click()
    page3.locator("div:nth-child(21) > .radio-field > .mdt-radio-list > .radio-list > li").first.click()
    page3.locator("div:nth-child(18) > .radio-field > .mdt-radio-list > .radio-list > li").first.click()
    page3.locator("div:nth-child(24) > .radio-field > .mdt-radio-list > .radio-list > li").first.click()
    page3.locator("div:nth-child(26) > .radio-field > .mdt-radio-list > .radio-list > li").first.click()
    page3.locator("div:nth-child(27) > .radio-field > .mdt-radio-list > .radio-list > li").first.click()
    page3.locator("div:nth-child(29) > .radio-field > .mdt-radio-list > .radio-list > li").first.click()
    page3.locator("li:nth-child(2)").first.click()
    page3.locator(".input").first.click()
    page3.locator(".input").first.fill("5")
    page3.locator("#decrement").first.click()
    page3.locator("#increment").first.click()
    page3.locator("div:nth-child(4) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > .input").click()
    page3.locator("div:nth-child(4) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > .input").fill("2")
    page3.locator("div:nth-child(4) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > #decrement > .fas").click()
    page3.locator("div:nth-child(4) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > #increment").click()
    page3.locator("div:nth-child(5) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > .input").click()
    page3.locator("div:nth-child(5) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > .input").fill("2")
    page3.locator("div:nth-child(5) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > #decrement").click()
    page3.locator("div:nth-child(5) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > #increment > .fas").click()
    page3.locator("div:nth-child(6) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > .input").click()
    page3.locator("div:nth-child(6) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > .input").fill("2")
    page3.locator("div:nth-child(6) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > #decrement").click()
    page3.locator("div:nth-child(6) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > #increment").click()
    page3.locator("div:nth-child(7) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > .input").click()
    page3.locator("div:nth-child(7) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > .input").fill("2")
    page3.locator("div:nth-child(7) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > #increment").click()
    page3.locator("div:nth-child(7) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > #decrement").click()
    page3.locator("div:nth-child(8) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > .input").click()
    page3.locator("div:nth-child(8) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > .input").fill("2")
    page3.locator("div:nth-child(8) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > #decrement").click()
    page3.locator("div:nth-child(8) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > #increment").click()
    page3.locator("div:nth-child(9) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > .input").click()
    page3.locator("div:nth-child(9) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > .input").fill("2")
    page3.locator("div:nth-child(9) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > #decrement").click()
    page3.locator("div:nth-child(9) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > #increment").click()
    page3.get_by_role("textbox", name="Please specify").click()
    page3.get_by_role("textbox", name="Please specify").fill("geses")
    file_path = "D:\\Andrija programer\\Playwrightv2\\Playwright\\tests\\UIzadaca.png"
    page3.on("filechooser", lambda file_chooser: file_chooser.set_files(file_path))
    page3.locator("input[type=\"file\"]").click()
    page3.locator("input[type=\"file\"]").set_input_files(file_path)
    page3.locator("div:nth-child(12) > .radio-field > .mdt-radio-list > .radio-list > li:nth-child(2)").click()
    page3.locator("div:nth-child(13) > .radio-field > .mdt-radio-list > .radio-list > li:nth-child(2)").click()
    page3.locator("div:nth-child(14) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > .input").click()
    page3.locator("div:nth-child(14) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > .input").fill("4")
    page3.locator("div:nth-child(14) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > #decrement > .fas").click()
    page3.locator("div:nth-child(14) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > #increment > .fas").click()
    page3.locator("div:nth-child(15) > .radio-field > .mdt-radio-list > .radio-list > li:nth-child(2)").click()
    page3.locator("div:nth-child(16) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > .input").click()
    page3.locator("div:nth-child(16) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > .input").fill("5")
    page3.locator("div:nth-child(16) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > #decrement").click()
    page3.locator("div:nth-child(16) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > #increment").click()
    page3.locator("div:nth-child(17) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > .input").click()
    page3.locator("div:nth-child(17) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > .input").fill("5")
    page3.locator("div:nth-child(17) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > #decrement > .fas").click()
    page3.locator("div:nth-child(17) > .mt-16 > div > div > .mdt-number-incrementer > .wrapper > #increment > .fas").click()
    page3.locator("div:nth-child(18) > .radio-field > .mdt-radio-list > .radio-list > li:nth-child(2)").click()
    page3.locator("textarea").click()
    page3.locator("textarea").fill("dg4w")
    page3.get_by_role("textbox", name="Please specify").nth(1).click()
    page3.get_by_role("textbox", name="Please specify").nth(1).fill("w3")
    page3.get_by_role("textbox", name="Please specify").nth(1).press("F1")
    page3.get_by_role("textbox", name="Please specify").nth(1).fill("33")
    page3.locator("div:nth-child(21) > .radio-field > .mdt-radio-list > .radio-list > li:nth-child(2)").click()
    page3.get_by_role("textbox").nth(3).click()
    page3.get_by_role("textbox").nth(3).fill("3gw3tw")
    page3.get_by_role("textbox", name="Please specify").nth(2).click()
    page3.get_by_role("textbox", name="Please specify").nth(2).fill("r2qr2qr2q")
    page3.locator("div:nth-child(24) > .radio-field > .mdt-radio-list > .radio-list > li:nth-child(2)").click()
    page3.locator("textarea").nth(2).click()
    page3.locator("textarea").nth(2).fill("2eda2a")
    page3.locator("div:nth-child(26) > .radio-field > .mdt-radio-list > .radio-list > li:nth-child(2)").click()
    page3.locator("div:nth-child(27) > .radio-field > .mdt-radio-list > .radio-list > li:nth-child(2)").click()
    page3.get_by_role("textbox", name="Please specify").nth(3).click()
    page3.get_by_role("textbox", name="Please specify").nth(3).fill("d2ada2")
    page3.locator("div:nth-child(29) > .radio-field > .mdt-radio-list > .radio-list > li:nth-child(2)").click()
    page3.get_by_text("Save and next").click()
    page3.get_by_role("textbox", name="Please choose").first.click()
    page3.get_by_text("single person household").click()
    page3.get_by_role("listitem", name="No").first.click()
    page3.get_by_role("listitem", name="Yes").first.click()
    page3.locator("div:nth-child(2) > .text-cut").first.click()
    page3.locator("div:nth-child(2) > .text-cut").first.fill("efsefs")
    page3.locator("input[type='file']").click()
    page3.locator("input[type='file']").set_input_files(file_path)


    
    page3.get_by_role("listitem", name="No").nth(1).click()
    page3.get_by_role("listitem", name="Yes").nth(1).click()
    page3.locator("div:nth-child(7) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").first.click()
    page3.locator("div:nth-child(7) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").first.fill("effesefs")
    page3.get_by_role("listitem", name="No").nth(2).click()
    page3.get_by_role("listitem", name="Yes").nth(2).click()
    page3.get_by_role("textbox", name="Please choose").nth(1).click()
    page3.get_by_text("Reconstruction/Renovation").click()
    page3.locator("div:nth-child(2) > .input-wrapper > .text-cut").click()
    page3.locator("div:nth-child(2) > .input-wrapper > .text-cut").fill("fesfesfes")
    page3.locator("div:nth-child(2) > div > div > div:nth-child(4) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").click()
    page3.locator("div:nth-child(2) > div > div > div:nth-child(4) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").fill("fesfesfes")
    page3.get_by_role("listitem", name="Security deposit").click()
    page3.get_by_role("listitem", name="Insurance solution").click()
    page3.get_by_role("textbox", name="Please choose").nth(2).click()
    page3.get_by_text("FirstCaution").click()
    page3.get_by_role("listitem", name="No").nth(3).click()
    page3.get_by_role("listitem", name="Yes").nth(3).click()
    page3.locator("div:nth-child(6) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").click()
    page3.locator("div:nth-child(6) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").fill("98732235")
    page3.locator("div:nth-child(3) > div > div > div:nth-child(7) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").click()
    page3.locator("div:nth-child(3) > div > div > div:nth-child(7) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").fill("wafwafafw")
    page3.locator("div:nth-child(8) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").click()
    page3.locator("div:nth-child(8) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").fill("rdgdrrdg")
    page3.locator("div:nth-child(2) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").click()
    page3.locator("div:nth-child(2) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").fill("rgddgrrddrg")
    page3.locator("textarea").first.click()
    page3.locator("textarea").first.fill("grdgrdgrdrrgdgr")
    page3.get_by_role("textbox", name="Current tenant").click()
    page3.get_by_text("No relation").click()
    page3.get_by_role("textbox", name="Already living in the").click()
    page3.get_by_text("Already living in the").click()
    page3.get_by_role("textbox", name="Please choose").nth(3).click()
    page3.get_by_text("Instagram").click()
    page3.locator("textarea").nth(1).click()
    page3.locator("textarea").nth(1).fill("grddgrgdrdgrgrd")
    page3.get_by_text("Save and next").click()
    page3.get_by_text("Add adult").click()
    page3.locator(".text-cut").first.click()
    page3.get_by_text("Mr.").click()
    page3.get_by_role("textbox", name="Please specify").first.click()
    page3.get_by_role("textbox", name="Please specify").first.fill("Andrija")
    page3.get_by_role("textbox", name="Please specify").nth(1).click()
    page3.get_by_role("textbox", name="Please specify").nth(1).fill("Soldo")
    page3.get_by_role("textbox", name="DD.MM.YYYY").first.click()
    page3.get_by_role("cell", name="3", exact=True).click()
    page3.get_by_role("textbox", name="Please specify").nth(2).click()
    page3.get_by_role("textbox", name="Please specify").nth(2).fill("wdaawdaw")
    page3.locator("div:nth-child(7) > .mt-16 > div > .mdt-select > .select-wrapper > .search > .mdt-input > .input-wrapper > .text-cut").click()
    page3.get_by_text("single").click()
    page3.get_by_role("textbox", name="Search...").first.click()
    page3.get_by_text("Switzerland", exact=True).click()
    page3.locator("div:nth-child(9) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").click()
    page3.locator("div:nth-child(9) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").fill("wdaadwawd")
    page3.get_by_role("textbox", name="DD.MM.YYYY").nth(1).click()
    page3.get_by_role("cell", name="3", exact=True).click()
    page3.get_by_role("textbox", name="Please choose").nth(2).click()
    page3.get_by_text("Main tenant").click()
    page3.get_by_role("textbox", name="123 45 67").first.click()
    page3.get_by_role("textbox", name="123 45 67").first.fill("333333333")
    page3.locator("div").filter(has_text=re.compile(r"^\+41$")).nth(3).click()
    page3.locator("#iti-1__item-ba").get_by_text("Bosnia and Herzegovina").click()
    page3.get_by_role("textbox", name="123 456").click()
    page3.get_by_role("textbox", name="123 456").fill("")
    page3.get_by_role("textbox", name="123 456").click()
    page3.get_by_role("textbox", name="123 456").click()
    page3.get_by_role("textbox", name="123 456").fill("63111111")
    page3.locator("input[type=\"email\"]").first.click()
    page3.locator("input[type=\"email\"]").first.fill("andrija@gmail.com")
    page3.locator("input[type=\"email\"]").nth(1).click()
    page3.locator("input[type=\"email\"]").nth(1).fill("andrija@gmail.com")
    page3.get_by_role("textbox", name="Please choose").nth(3).click()
    page3.get_by_text("Own home").click()
    page3.locator("div:nth-child(13) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").click()
    page3.locator("div:nth-child(13) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").fill("22253")
    page3.get_by_role("spinbutton").first.click()
    page3.get_by_role("spinbutton").first.fill("325235")
    page3.locator("div:nth-child(15) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").click()
    page3.locator("div:nth-child(15) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").fill("fawwfawf")
    page3.get_by_role("textbox", name="Search...").nth(1).click()
    page3.get_by_text("Switzerland", exact=True).click()
    page3.get_by_role("textbox", name="DD.MM.YYYY").nth(2).click()
    page3.get_by_role("cell", name="3", exact=True).click()
    page3.get_by_role("listitem", name="No").first.click()
    page3.get_by_role("listitem", name="Yes").first.click()
    page3.get_by_role("listitem", name="No").nth(1).click()
    page3.get_by_role("listitem", name="Yes").nth(1).click()
    page3.locator("div:nth-child(20) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").click()
    page3.locator("div:nth-child(20) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").fill("f234")
    page3.get_by_role("spinbutton").nth(1).click()
    page3.get_by_role("spinbutton").nth(1).fill("341")
    page3.locator("div:nth-child(22) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").click()
    page3.locator("div:nth-child(22) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").fill("awffatgag")
    page3.get_by_role("listitem", name="No").nth(2).click()
    page3.get_by_role("listitem", name="Yes").nth(2).click()
    page3.get_by_role("textbox", name="DD.MM.YYYY").nth(3).click()
    page3.get_by_role("cell", name="3", exact=True).click()
    page3.locator("div:nth-child(25) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").click()
    page3.locator("div:nth-child(25) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").fill("6426226")
    page3.get_by_role("listitem", name="No").nth(3).click()
    page3.get_by_role("listitem", name="Yes").nth(3).click()
    page3.locator("div:nth-child(4) > div > div > div:nth-child(3) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").click()
    page3.locator("div:nth-child(4) > div > div > div:nth-child(3) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").fill("fwafwafwa")
    page3.locator("div:nth-child(4) > .radio-field > .mdt-radio-list > .radio-list > li").first.click()
    page3.get_by_text("Insurance Personal liability").click()
    page3.locator("div:nth-child(4) > .radio-field > .mdt-radio-list > .radio-list > li:nth-child(2)").click()
    page3.locator("div:nth-child(5) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").click()
    page3.locator("div:nth-child(5) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").fill("fwafwafw")
    page3.locator("div:nth-child(6) > .radio-field > .mdt-radio-list > .radio-list > li").first.click()
    page3.locator("div:nth-child(6) > .radio-field > .mdt-radio-list > .radio-list > li:nth-child(2)").click()
    page3.get_by_role("textbox", name="Secondary level I").click()
    page3.get_by_text("Tertiary level").click()
    page3.get_by_role("textbox", name="Please choose").nth(4).click()
    page3.get_by_text("Full-time (90-100%)").click()
    page3.locator("div:nth-child(5) > div > div > div:nth-child(4) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").click()
    page3.locator("div:nth-child(5) > div > div > div:nth-child(4) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").fill("wfafawwfafwa")
    page3.get_by_role("listitem", name="Permanent").click()
    page3.get_by_role("listitem", name="Temporary").click()
    page3.get_by_role("textbox", name="DD.MM.YYYY").nth(4).click()
    page3.get_by_role("cell", name="10").click()
    page3.get_by_role("listitem", name="Not terminated").click()
    page3.get_by_role("listitem", name="Terminated", exact=True).click()
    page3.get_by_role("listitem", name="Not terminated").click()
    page3.locator("div:nth-child(5) > div > div > div:nth-child(9) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").click()
    page3.locator("div:nth-child(5) > div > div > div:nth-child(9) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").fill("wfawfawfwafw")
    page3.locator("div:nth-child(10) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").click()
    page3.locator("div:nth-child(10) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").fill("53253253")
    page3.get_by_role("spinbutton").nth(2).click()
    page3.get_by_role("spinbutton").nth(2).fill("1214")
    page3.locator("div:nth-child(12) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").click()
    page3.locator("div:nth-child(12) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").fill("awddwadwa")
    page3.locator("div:nth-child(5) > div > div > div:nth-child(13) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").click()
    page3.locator("div:nth-child(5) > div > div > div:nth-child(13) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").fill("wdawawadwa")
    page3.get_by_role("textbox", name="123 45 67").nth(1).click()
    page3.get_by_role("textbox", name="123 45 67").nth(1).fill("333333333")
    page3.locator("input[type=\"email\"]").nth(2).click()
    page3.locator("input[type=\"email\"]").nth(2).fill("w@gmail.com")
    page3.get_by_role("textbox", name="CHF 0 - CHF 10’").click()
    page3.get_by_text("over CHF 200’").click()
    page3.get_by_role("spinbutton").nth(3).click()
    page3.get_by_role("spinbutton").nth(3).fill("55555")
    page3.get_by_role("spinbutton").nth(4).click()
    page3.get_by_role("spinbutton").nth(4).fill("5555555555")
    page3.get_by_role("listitem", name="CreditTrust certificate").click()
    page3.get_by_role("listitem", name="Excerpt from the debt").click()
    page3.on("filechooser", lambda file_chooser: file_chooser.set_files(file_path))
    page3.locator(".input-file").first.click()
    page3.locator(".input-file").first.set_input_files(file_path)

    page3.locator("input[type=\"file\"]").first.click()
    page3.locator("input[type=\"file\"]").first.set_input_files(file_path)

    page3.locator("input[type=\"file\"]").first.click()
    page3.locator("input[type=\"file\"]").first.set_input_files(file_path)

    page3.locator("input[type=\"file\"]").first.click()
    page3.locator("input[type=\"file\"]").first.set_input_files(file_path)

    page3.locator("input[type=\"file\"]").first.click()
    page3.locator("input[type=\"file\"]").first.set_input_files(file_path)

    page3.locator("input[type=\"file\"]").click()
    page3.locator("input[type=\"file\"]").set_input_files(file_path)

    page3.get_by_role("checkbox", name="I hereby confirm that").check()
    page3.get_by_text("Save", exact=True).click()
    page3.get_by_text("Add adult").click()
    page3.locator(".text-cut").first.click()
    page3.get_by_text("Ms.").click()
    page3.get_by_role("textbox", name="Please specify").first.click()
    page3.get_by_role("textbox", name="Please specify").first.fill("d")
    page3.get_by_role("textbox", name="Please specify").first.press("CapsLock")
    page3.get_by_role("textbox", name="Please specify").nth(1).click()
    page3.get_by_role("textbox", name="Please specify").nth(1).fill("WDADAW")
    page3.get_by_role("textbox", name="Please specify").nth(1).press("CapsLock")
    page3.get_by_role("textbox", name="DD.MM.YYYY").first.click()
    page3.get_by_role("cell", name="3", exact=True).click()
    page3.get_by_role("textbox", name="Please specify").nth(2).click()
    page3.locator("div:nth-child(7) > .mt-16 > div > .mdt-select > .select-wrapper > .search > .mdt-input > .input-wrapper > .text-cut").click()
    page3.get_by_text("single").click()
    page3.get_by_role("textbox", name="Search...").first.click()
    page3.get_by_text("Switzerland", exact=True).click()
    page3.locator("div:nth-child(9) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").click()
    page3.locator("div:nth-child(9) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").fill("dwa")
    page3.get_by_role("textbox", name="Please choose").nth(2).click()
    page3.get_by_text("Spouse, registered partnership").click()
    page3.get_by_role("textbox", name="123 45 67").first.click()
    page3.get_by_role("textbox", name="123 45 67").first.fill("333333333")
    page3.locator("input[type=\"email\"]").first.click()
    page3.locator("input[type=\"email\"]").first.fill("d@gmaio.com")
    page3.locator("input[type=\"email\"]").nth(1).click()
    page3.locator("input[type=\"email\"]").nth(1).fill("d@gmaio.com")
    page3.locator("div:nth-child(13) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").click()
    page3.locator("div:nth-child(13) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").fill("3")
    page3.get_by_role("spinbutton").first.click()
    page3.get_by_role("spinbutton").first.fill("4")
    page3.locator("div:nth-child(15) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").click()
    page3.locator("div:nth-child(15) > .mt-16 > .mdt-input > .input-wrapper > .text-cut").fill("adwa")
    page3.get_by_role("textbox", name="Search...").nth(1).click()
    page3.get_by_role("listitem").filter(has_text="Aruba").locator("div").click()
    page3.get_by_role("textbox", name="DD.MM.YYYY").nth(2).click()
    page3.get_by_role("cell", name="3", exact=True).click()
    page3.get_by_role("textbox", name="Please choose").nth(4).click()
    page3.get_by_text("Retired", exact=True).click()
    page3.get_by_role("listitem", name="CreditTrust certificate").click()
    page3.get_by_role("checkbox", name="I hereby confirm that").check()
    page3.get_by_text("Save", exact=True).click()
    page3.locator("div:nth-child(2) > .person-card > .header > .actions > .fa-solid").click()
    page3.get_by_role("textbox", name="Please choose").first.click()
    page3.get_by_text("Other").click()
    page3.get_by_text("I hereby confirm that").click()
    page3.get_by_text("Save", exact=True).click()
    page3.locator("div:nth-child(2) > .person-card > .header > .actions > .fa-regular").click()
    page3.get_by_text("Delete", exact=True).nth(3).click()
    page3.get_by_text("Save and next").click()
    page3.get_by_role("checkbox", name="Should the prospective tenant").check()
    page3.get_by_role("checkbox", name="I confirm that I have").check()
    page3.get_by_role("checkbox", name="I have read the privacy").check()
    page3.get_by_text("Save").click()

    # ---------------------
    context.close()
    browser.close()


if __name__ == "__main__":
    with sync_playwright() as playwright:
        test_run(playwright)